# Generated by Django 4.2 on 2025-03-20 07:47

from django.db import migrations, models
import utils.genaerate_code


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='code',
            field=models.CharField(default=utils.genaerate_code.generate_code, max_length=75),
        ),
    ]
